### ISSUE TITLE
The data link is not working

### ISSUE THREAD

**Issue by zeeshanalipanhwar** [IssamLaradji/looc#1]
Hi, the [link](http://agamenon.tsc.uah.es/Personales/rlopez/data/trancos/TRANCOS_v3.tar.gz) to the data is not working. Kindly update it.

**Comment by IssamLaradji** [comment]
It looks like it is a problem with the Trancos server, which is managed by this team: https://pgram.com/dataset/trancos-overlapping-car-crowds/

Hopefully they could fix it on their side.
